### PR TITLE
Fix for feedback method

### PR DESCRIPTION
**Pull request by MichaelBaker**
I had to make a change to this repo in order to get feedback working for our project. It now reads messages correctly from the APNS feedback service. Would you mind merging in my changes and bumping up the version on Rubygems?

### CODE REVIEW

**Comment by NicosKaralis** [comment]
i still cant read the feedback from my app
on your code and on the "official" code

it just returns a empty array all the time

**Comment by MichaelBaker** [comment]
Have you verified that the SSL connection is being established successfully? Can your SSL connection read anything?

**Comment by NicosKaralis** [comment]
Yes, i can send notifications, because the two methods (`open_connection`, and `open_feedback_connection`) are the same i can't see why the ssl connection is not being opened.

And my connection sometimes read something. The problem is: the bytes read are not compatible with apple documentation.

The minimum number of bytes read are 38 and the first 4 are a timestamp, the 5º are a number and the other are the token. But the token always change, and the timestamp always return some data around 1979-81

**Comment by MichaelBaker** [comment]
Are you on the APNS sandbox server or the production server? Also, can you verify that it's reading exactly 38 bytes from the socket and no fewer? If you're on the production server and the correct number of bytes are getting read then I'm not sure what the problem is.

**Comment by NicosKaralis** [comment]
I'm using production APNS, and i have a small number of devices receiving pushes

using this:

```
while b = f.readbyte
  puts b
end
```

i can read 38 bytes, so i think the number of bytes are right

I have tried every solution, and still can read the feedback, everything seems normal to me

**Comment by MichaelBaker** [comment]
In your example you use `f`. Is that the `f` from the old version of the code? Make sure you're reading from `ssl` and not `sock`. I had a similar problem to yours and it was because the old code reads from `sock` so it was reading encrypted data, where as `ssl` decrypts the data.

**Comment by NicosKaralis** [comment]
currently i'm using: `f = ssl.read(38)` but this returns nothing at all.

if i change to `f = sock.read(38)` then i receive something, illegible, but something

**Comment by MichaelBaker** [comment]
That's the problem then. You need to investigate why you can't read from the SSL connection.

**Comment by NicosKaralis** [comment]
Found, thanks.

The problems was: i wasn't creating data to be displayed. The feedback connection only returns device tokens of devices that could not receive the notification because the user deleted the app.

To fix it i did this:
1. Installed my app
2. Send a push to the device
3. After that remove the app
4. Send another push (this time it won't arrive)
5. Now the first feedback will read this token

now everything seems to work, thanks

**Comment by MichaelBaker** [comment]
Cool, glad you got it figured out.

**Pull request merged**
